services:
  frontend:
    build: ./app
    ports: 
      - "8000:7860"
  news-scraper:
    build: ./news-scraper
    ports:
      - "8001:8000"
  summarizer:
    build: ./summarizer
    ports:
      - "8002:8000"
  vllm-server:
    image: vllm/vllm-openai:v0.6.6
    container_name: vllm-server
    ports:
      - "8003:8000"
    ipc: host
    command: ["--model", "facebook/bart-large-cnn", "--served-model-name", "bart-large-cnn"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  